## 넘파이 패키지 이용하기
* 배열 또는 벡터 계산을 위한 패키지
* ndarray 자료형을 이용.
* array = 리스트와 같은 개체 중 하나, 어레이는 배열 전체를 말한다. 파이썬은 배열이 없지만, 넘파이는 C로 돌아간다고 한다.
* array([1, 2, 3, 6]) 이와 같이 표시한다.
<br><br>
* 배열 생성 : arr = np.randam.randin(5, 8) -> (5, 8) 배열이 만들어진다. 랜덤이므로 수는 무작위.
* 배열 연산 : 일반 연산자 이용
* 단, 행렬곱은 * (성분곱) 대신 arr1.dot(arr2) 이용
* 판다스와 넘파이는 인덱싱 하는 순서가 서로 다르므로 주의해야 한다.

## 넘파이 파일 처리
* 판다스와는 다른 차이가 있다. 
* 판다스는 파일로 내보냈을 때 사람이 볼 수 있게끔 보여준다. 하지만 그렇게 하면 처리 속도에서 좋지 않다. 인코딩도 해야되고..
* 넘파이는 컴퓨터가 처리하는 방식 그대로 저장한다. (바이너리 형식이어서 판다스의 테이블 파일보다는 경제적이다.)
* 하지만 넘파이 파일이 압축을 하지 않기 때문에 용량이 좀 크다.
* arr = np.load('filename.npy')


In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [4]:
arr[3]

4

In [7]:
arr[-6:-1]

array([1, 2, 3, 4, 5])

In [8]:
arr[-8:-1]

array([1, 2, 3, 4, 5])

In [9]:
arr[:99]

array([1, 2, 3, 4, 5, 6])

In [10]:
arr[99]

IndexError: index 99 is out of bounds for axis 0 with size 6

* 인덱싱을 하면 오류가 나는데 슬라이싱을 하면 뜬다! 왜 그럴까?
* C 언어의 논리로 동작하기 때문인데..
* 파이썬은 할당되지 않은 값은 취급하지 않으나
* C 언어에서는 취급을 하게 된다.

In [11]:
# 어레이에서는 각자 값들을 비교하여 하나씩 결과가 나온다.
# 어레이는 전체 묶음? 이 별로 의미가 없다. 

arr[-999:99] == arr

array([ True,  True,  True,  True,  True,  True])

In [12]:
[1,2,3] == [1,2,3]

True

In [13]:
# 리스트에서는 전체 리스트가 맞는지 한번만 결과가 나온다.

list1 = [1,2,3]

In [14]:
list1[:] == list1

True

In [16]:
# 어레이에서 전체가 일치하는지 확인하기 위해서는
# 리스트를 씌워서 확인하는 방법을 사용할 수 있다.

list(arr[-999:99]) == list(arr)

True

In [52]:
# 랜덤 어레이 생성.. 이는 인덱싱도 가능하다.

np.random.randint([5,8])[0]


0

In [53]:
np.random.randint([(1,6),(1,6)])

array([[0, 5],
       [0, 5]])

## 실습 - 주사위 게임 만들기
* numpy 패키지를 이용해 주사위 게임 만들기
1. 컴퓨터는 두 숫자를 랜덤하게 받아낸다.
1. 두 숫자는 육면체 주사위 눈의 그것과 같다.
1. 처음에는 사용자에게 값을 알려주지 않고, 첫 번째 주사위가 두 번째 주사위의 눈보다 큰지 물어본다.
1. 사용자에게 큰지, 작은지 응답을 받고, 맞췄는지 출력해준다.
1. 해당 프로세스를 반복해서 할 수 있도록 한다.(입력에 따라 종료할 수도 있게 한다.)

In [59]:
def 주사위게임():
    a = np.random.randint(1,6)
    b = np.random.randint(1,6)

    ans = input('첫 번째 주사위가 두 번째 주사위의 눈보다 큽니까? Y / N  :  ')

    if ans == 'Y':

        if a > b:
            print('맞았습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()
        else:
            print('틀렸습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()

    if ans == 'N':

        if a > b:
            print('틀렸습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()
        else:
            print('맞았습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()


ind = 0          
            
while ind == 0:
    
    주사위게임()
    
    restart = input('다시 하시겠습니까? Y / N : ')  
    
    if restart == 'Y':
        continue
        
    elif restart == 'N':
        print('종료합니다.')
        ind += 1
        
    else:
        print('잘못된 값을 입력했습니다. 종료합니다.')
        ind += 1
        

        


첫 번째 주사위가 두 번째 주사위의 눈보다 큽니까? Y / N  :  Y
틀렸습니다.
첫 번째 주사위 :  2
두 번째 주사위 :  4

다시 하시겠습니까? Y / N : dddddd
잘못된 값을 입력했습니다. 종료합니다.


In [72]:
np.random.randint([6,6]) + 1

array([1, 6])

In [ ]:
def 주사위게임():
    a = np.random.randint(1,6)
    b = np.random.randint(1,6)

    ans = input('첫 번째 주사위가 두 번째 주사위의 눈보다 큽니까? Y / N  :  ')

    if ans == 'Y':

        if a > b:
            print('맞았습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()
        else:
            print('틀렸습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()

    if ans == 'N':

        if a > b:
            print('틀렸습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()
        else:
            print('맞았습니다.')
            print('첫 번째 주사위 : ', a)
            print('두 번째 주사위 : ', b)
            print()


ind = 0          
            
while ind == 0:
    
    주사위게임()
    
    restart = input('다시 하시겠습니까? Y / N : ')  
    
    if restart == 'Y':
        continue
        
    elif restart == 'N':
        print('종료합니다.')
        ind += 1
        
    else:
        print('잘못된 값을 입력했습니다. 종료합니다.')
        ind += 1
        

        


In [60]:

dice_num = int(input('몇개의 주사위를 사용하겠나요? : '))
dice_li = []

for i in range(dice_num):
    a = np.random.randint(1,12)
    dice_li.append(a)
    
dice_li
    

몇개의 주사위를 사용하겠나요?3


[1, 5, 1]

In [73]:
"hello,'world'"

"hello,'world'"

In [74]:
'hello'world''

SyntaxError: invalid syntax (953303920.py, line 1)

In [75]:
# 작은 따옴표 안에 작은 따옴표를 넣고 싶을 때...
'hello, \'world\''

"hello, 'world'"

In [79]:
# 작은따옴표 세 개로 줄바꿈 엔터를 허용할 수 있다.

print('''안
녕
'하'
세
요''')

안
녕
'하'
세
요


In [84]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
# 원래 리스트는 아래와 같이 주르륵 나오지만...
# 어레이의 경우 원래 행렬이기 때문에 행렬로 들어가게 된다.

[[1,2,3],[4,5,6],[7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [85]:
# 괄호에 주의

print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
arr_2d[1,1]

5

In [92]:
arr_2d[1][1]

5

In [100]:
arr_2d[:1,:2]

array([[1, 2]])

In [97]:
import pandas as pd

df = pd.DataFrame(arr_2d)

In [101]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [99]:
df.iloc[:1,:2]

0  1
0  1  2

* 아니 근데.. 넣었을때 결과값이 똑같이 나오는데 왜 방식이 완전히 다르대?
* 라고 이야기하면.. 넘파이는 판다스를 Transform 한 것(1사분면 -> 3사분면)을 다시 1사분면에서 보는것 처럼 나타내주는 것이기 때문이다.
* 실제로는 축이 완전히 반대임.

---
## 복습

In [102]:
# 이와 같이 함수 안에서 패키지를 불러와서 그 안에서만 쓰는 것은 꽤나 유용하다.

def func1():
    import math
    print (math.log(4))
    print (math.log(5))
    print (math.log(6))

In [103]:
func1()

1.3862943611198906
1.6094379124341003
1.791759469228055


In [2]:
1+1 # plus()

In [9]:
list1 = [1,2,3]

In [3]:
list2 = [1,2,3,4,5]

In [32]:
def plus(x,y):
    return x + y

In [35]:
list1 = [1,2,3]

def append2(x):
    global list1
    plus(list1,[x])

    
append2(5)    
list1

[1, 2, 3]

In [37]:
append2(5)

In [38]:
import pandas as pd

In [56]:
df = pd.read_csv('C:/Users/user/Desktop/lecfile/nov/221110/test.csv')

In [41]:
df.head(2)

PassengerId  Pclass                              Name     Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    male  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   

   Parch  Ticket    Fare Cabin Embarked  
0      0  330911  7.8292   NaN        Q  
1      0  363272  7.0000   NaN        S

## 실습 : 데이터프레임 처리하기 - 리스트컴프리헨션

* df 의 Age column에서 대상이 20 살 이상인지를 판별하는 것으로 데이터를 대체한다.
* 해당 연산은 아래의 코드를 이용해서 한다.
* fn1을 새로 만드는 것, col1을 Age 로 이름을 바꾸는 것 이외에는 허용하지 않는다.

In [44]:
df['Age'][0]

34.5

In [54]:

def fn1(x):
    if x >= 20:
        return '20살 이상'
    
    else:
        return '20살 미만'
    
    
[fn1(i) for i in df['Age']]

In [55]:
df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex     Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  20살 이상      0      0              330911    7.8292   NaN        Q  
1    female  20살 이상      1      0              363272    7.0000   NaN        S  
2      male  20살 이상      0      0              240276    9.6875   NaN        Q  
3      male  20살 이상      0      0              315154    8.6625   NaN        S  
4    female  20살 이상      1      1             3101298   12.2875   NaN        S  
..      ...     ...    ...    ...                 ...       ...   ...      ...  
413    male  20살 미만      0      0           A.5. 3236    8.0500   NaN        S  
414  female  20살 이상      0      0            PC 17758  108.9000  C105        C  
415    male  20살 이상      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male  20살 미만      0      0              359309    8.0500   NaN        S  
417    male  20살 미만      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [58]:
# 리스트컴프리헨션을 돌리는 것 만으로 연산을 하도록 만들 수 있다고 한다.
# 근데 함수 내부 인디케이터 더해놓으면 외부..가 바뀌는건 아닐텐데?

ind = 0

def fn1(i):
    global ind
    global df
    
    df.loc[ind, 'Age'] = i >= 20
    ind += 1
    
    
[fn1(i) for i in df['Age']]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,

In [59]:
df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex    Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male   True      0      0              330911    7.8292   NaN        Q  
1    female   True      1      0              363272    7.0000   NaN        S  
2      male   True      0      0              240276    9.6875   NaN        Q  
3      male   True      0      0              315154    8.6625   NaN        S  
4    female   True      1      1             3101298   12.2875   NaN        S  
..      ...    ...    ...    ...                 ...       ...   ...      ...  
413    male  False      0      0           A.5. 3236    8.0500   NaN        S  
414  female   True      0      0            PC 17758  108.9000  C105        C  
415    male   True      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male  False      0      0              359309    8.0500   NaN        S  
417    male  False      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [60]:
df['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...                     
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

## 실습 : df 데이터프레임의 Name column에서
* 구두점이 몇 개 있는지 리스트로 나타내보자.
* 띄어쓰기가 몇 개 있는지, 개수가 두 개 이상인지 알아보자.
* (다 했다면) 대문자를 모두 소문자로 바꾸어 해당 데이터프레임에 반영해보자.

In [61]:
# 구두점이 몇 개 있는지 리스트로 나타내보자.

machim_num = []

for i in df['Name']:
    a = i.count(',')
    b = i.count('.')
    machim_num.append(a + b)
    
machim_num

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,


In [64]:
for i in df['Name']:
    c = i.count(' ')
    
    print('띄어쓰기', c, '개')

띄어쓰기 2 개
띄어쓰기 4 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 5 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 5 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 5 개
띄어쓰기 2 개
띄어쓰기 6 개
띄어쓰기 5 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 4 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 4 개
띄어쓰기 6 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 5 개
띄어쓰기 6 개
띄어쓰기 3 개
띄어쓰기 4 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 5 개
띄어쓰기 6 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 6 개
띄어쓰기 5 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 7 개
띄어쓰기 3 개
띄어쓰기 3 개
띄어쓰기 4 개
띄어쓰기 4 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 4 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 6 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 7 개
띄어쓰기 2 개
띄어쓰기 4 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 3 개
띄어쓰기 6 개
띄어쓰기 3 개
띄어쓰기 4 개
띄어쓰기 3 개
띄어쓰기 7 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 4 개
띄어쓰기 4 개
띄어쓰기 3 개
띄어쓰기 2 개
띄어쓰기 2 개
띄어쓰기 4 개
띄어쓰기 2 개
띄어쓰기 3 개
띄

In [65]:
df['Name'] = [i.lower() for i in df['Name']]

In [66]:
df

PassengerId  Pclass                                          Name  \
0            892       3                              kelly, mr. james   
1            893       3              wilkes, mrs. james (ellen needs)   
2            894       2                     myles, mr. thomas francis   
3            895       3                              wirz, mr. albert   
4            896       3  hirvonen, mrs. alexander (helga e lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            spector, mr. woolf   
414         1306       1                  oliva y ocana, dona. fermina   
415         1307       3                  saether, mr. simon sivertsen   
416         1308       3                           ware, mr. frederick   
417         1309       3                      peter, master. michael j   

        Sex    Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male   True      0      0              330911    7.8292   NaN        Q  
1    female   True      1      0              363272    7.0000   NaN        S  
2      male   True      0      0              240276    9.6875   NaN        Q  
3      male   True      0      0              315154    8.6625   NaN        S  
4    female   True      1      1             3101298   12.2875   NaN        S  
..      ...    ...    ...    ...                 ...       ...   ...      ...  
413    male  False      0      0           A.5. 3236    8.0500   NaN        S  
414  female   True      0      0            PC 17758  108.9000  C105        C  
415    male   True      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male  False      0      0              359309    8.0500   NaN        S  
417    male  False      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]